//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaintainEvision.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeError
    {
        public int SysId { get; set; }
        public string Vender { get; set; }
        public string ProductType { get; set; }
        public string ErrorCode { get; set; }
        public string CodeType { get; set; }
        public string EngDesc { get; set; }
        public string ChtDesc { get; set; }
        public string ChsDesc { get; set; }
        public string Duty { get; set; }
        public string Active { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> ModiDate { get; set; }
        public string ModiUser { get; set; }
    }
}
