//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaintainEvision.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EvisionConnectionString : DbContext
    {
        public EvisionConnectionString()
            : base("name=EvisionConnectionString")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CodeError> CodeError { get; set; }
        public virtual DbSet<CodeReason> CodeReason { get; set; }
        public virtual DbSet<UserId> UserId { get; set; }
        public virtual DbSet<UserSystem> UserSystem { get; set; }
    }
}
