//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaintainEvision.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSystem
    {
        public string UserId { get; set; }
        public string System { get; set; }
        public string Role { get; set; }
        public string Region { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> ModiDate { get; set; }
        public string ModiUser { get; set; }
    }
}
